language:
  - node_js

node_js:
  - "7"

install:
  - 'npm install'
  - 'npm install -g codecov'

script:
  - 'npm run unit'
  - 'codecov'

after_success:
  - |
    if [ $TRAVIS_BRANCH == "master" ]; then
      curl https://tigertracker.rit.edu:9988/deploy/TAK9Nu7g4GXIS8jfwzn8
    fi
  - |
    if [ $TRAVIS_BRANCH == "develop" ]; then
      curl https://tigertrackerstage.rit.edu:9988/deploy/JjttpRkSfMkX5ma3l7jL
    fi
